// Synthetic Apollo-shaped leads for dev/demo when APOLLO_API_KEY lacks paid plan.
// Real scoring engine runs against these — proves the pipeline end-to-end.
import type { Lead } from './types'

export const MOCK_APOLLO_POOL: Lead[] = [
  {
    name: 'Priya Sharma', designation: 'VP Platform Engineering', company: 'Razorpay',
    linkedin_url: 'https://linkedin.com/in/priya-sharma-razorpay', email: null,
    first_name: 'Priya', last_name: 'Sharma', title: 'VP Platform Engineering',
    headline: 'VP Platform Engineering at Razorpay · Building payment infra for India',
    seniority: 'vp', departments: ['engineering'],
    city: 'Bengaluru', state: 'Karnataka', country: 'India',
    company_domain: 'razorpay.com', company_website: 'https://razorpay.com',
    twitter_url: null, github_url: null, facebook_url: null,
    apollo_person_id: 'mock-priya', apollo_organization_id: 'mock-rzp',
    email_status: null, enriched: false,
  },
  {
    name: 'David Park', designation: 'Director of Engineering, Infrastructure', company: 'Retool',
    linkedin_url: 'https://linkedin.com/in/david-park-retool', email: null,
    first_name: 'David', last_name: 'Park', title: 'Director of Engineering, Infrastructure',
    headline: 'Director of Engineering at Retool · Ex-Stripe · Platform & Infra',
    seniority: 'director', departments: ['engineering'],
    city: 'San Francisco', state: 'CA', country: 'United States',
    company_domain: 'retool.com', company_website: 'https://retool.com',
    twitter_url: 'https://twitter.com/davidpark', github_url: null, facebook_url: null,
    apollo_person_id: 'mock-david', apollo_organization_id: 'mock-retool',
    email_status: null, enriched: false,
  },
  {
    name: 'Rahul Iyer', designation: 'VP Engineering', company: 'Postman',
    linkedin_url: 'https://linkedin.com/in/rahul-iyer-postman', email: null,
    first_name: 'Rahul', last_name: 'Iyer', title: 'VP Engineering',
    headline: 'VP Engineering at Postman · Scaling API tooling for 30M+ developers',
    seniority: 'vp', departments: ['engineering'],
    city: 'Bengaluru', state: 'Karnataka', country: 'India',
    company_domain: 'postman.com', company_website: 'https://postman.com',
    twitter_url: null, github_url: null, facebook_url: null,
    apollo_person_id: 'mock-rahul', apollo_organization_id: 'mock-postman',
    email_status: null, enriched: false,
  },
  {
    name: 'Lin Zhao', designation: 'Head of Platform', company: 'Vercel',
    linkedin_url: 'https://linkedin.com/in/lin-zhao-vercel', email: null,
    first_name: 'Lin', last_name: 'Zhao', title: 'Head of Platform',
    headline: 'Head of Platform at Vercel · Series D · Edge infra at scale',
    seniority: 'head', departments: ['engineering'],
    city: 'Singapore', state: null, country: 'Singapore',
    company_domain: 'vercel.com', company_website: 'https://vercel.com',
    twitter_url: null, github_url: null, facebook_url: null,
    apollo_person_id: 'mock-lin', apollo_organization_id: 'mock-vercel',
    email_status: null, enriched: false,
  },
  {
    name: 'James OConnell', designation: 'CTO', company: 'Hightouch',
    linkedin_url: 'https://linkedin.com/in/james-oconnell-hightouch', email: null,
    first_name: 'James', last_name: 'OConnell', title: 'CTO',
    headline: 'CTO & Co-founder at Hightouch · Reverse ETL · Series B',
    seniority: 'c_suite', departments: ['engineering'],
    city: 'San Francisco', state: 'CA', country: 'United States',
    company_domain: 'hightouch.com', company_website: 'https://hightouch.com',
    twitter_url: 'https://twitter.com/jamesoc', github_url: 'https://github.com/jamesoc', facebook_url: null,
    apollo_person_id: 'mock-james', apollo_organization_id: 'mock-hightouch',
    email_status: null, enriched: false,
  },
  {
    name: 'Ananya Krishnan', designation: 'VP Infrastructure', company: 'Zerodha',
    linkedin_url: 'https://linkedin.com/in/ananya-krishnan-zerodha', email: null,
    first_name: 'Ananya', last_name: 'Krishnan', title: 'VP Infrastructure',
    headline: 'VP Infrastructure at Zerodha · FinTech platform at scale',
    seniority: 'vp', departments: ['engineering'],
    city: 'Bengaluru', state: 'Karnataka', country: 'India',
    company_domain: 'zerodha.com', company_website: 'https://zerodha.com',
    twitter_url: null, github_url: null, facebook_url: null,
    apollo_person_id: 'mock-ananya', apollo_organization_id: 'mock-zerodha',
    email_status: null, enriched: false,
  },
  {
    name: 'Sofia Martinez', designation: 'Senior Engineering Manager', company: 'Linear',
    linkedin_url: 'https://linkedin.com/in/sofia-martinez-linear', email: null,
    first_name: 'Sofia', last_name: 'Martinez', title: 'Senior Engineering Manager',
    headline: 'Senior Engineering Manager at Linear',
    seniority: 'manager', departments: ['engineering'],
    city: 'Berlin', state: null, country: 'Germany',
    company_domain: 'linear.app', company_website: 'https://linear.app',
    twitter_url: null, github_url: null, facebook_url: null,
    apollo_person_id: 'mock-sofia', apollo_organization_id: 'mock-linear',
    email_status: null, enriched: false,
  },
  {
    name: 'Vikram Rao', designation: 'Head of Engineering, Platform', company: 'CRED',
    linkedin_url: 'https://linkedin.com/in/vikram-rao-cred', email: null,
    first_name: 'Vikram', last_name: 'Rao', title: 'Head of Engineering, Platform',
    headline: 'Head of Platform Engineering at CRED · ex-Flipkart',
    seniority: 'head', departments: ['engineering'],
    city: 'Bengaluru', state: 'Karnataka', country: 'India',
    company_domain: 'cred.club', company_website: 'https://cred.club',
    twitter_url: null, github_url: null, facebook_url: null,
    apollo_person_id: 'mock-vikram', apollo_organization_id: 'mock-cred',
    email_status: null, enriched: false,
  },
]
